version: 0.2

env:
  secrets-manager:
    SONAR_HOST_URL: prod-new:SONAR_HOST_URL
    SONAR_TOKEN: prod-new:SONAR_TOKEN

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y unzip wget
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-*.zip

  build:
    commands:
      - echo Running SonarQube Scan
      - |
        ./sonar-scanner-*/bin/sonar-scanner \
        -Dsonar.projectKey=myapp \
        -Dsonar.sources=. \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN \
        -Dsonar.qualitygate.wait=true
