version: 0.2

env:
  secrets-manager:
    SONAR_HOST_URL: prod:http://13.127.161.13:9000
    SONAR_TOKEN: prod:sqp_d7e3e24b1b22379c06e1b27b44802388cca04ea6

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y unzip wget
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-*.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-*/bin

  build:
    commands:
      - sonar-scanner \
        -Dsonar.projectKey=myapp \
        -Dsonar.sources=. \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN \
        -Dsonar.qualitygate.wait=true
